### ISSUE TITLE
Does this have swift support?

### ISSUE THREAD

**Issue by Knights22** [cwRichardKim/RKCardView#7]

**Comment by cwRichardKim** [comment]
How do you mean? Swift projects can use it, just like they can use any obj-c class, but there is no swift equivalent (it wouldn't be hard to make though)

**Comment by Knights22** [comment]
Ok, thanks Richard, you right, i 'll give it a shot, it should be something like:
let cardView = RKCardView(x origin, y origin, card width, card height)
