### ISSUE TITLE
This will cause the effect to appear broken until opacity returns to 1.

### ISSUE THREAD

**Issue by Knights22** [cwRichardKim/RKCardView#8]
I keep on getting this notification, should i just ignore it?
<UIVisualEffectView 0x136e514c0> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by cwRichardKim** [comment]
I'm not sure I understand. What's the context?

**Comment by Knights22** [comment]
Wow, i totally didn't realise that i did not post the error message correctly, here it is:
<UIVisualEffectView 0x155d51c30> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by Knights22** [comment]
Wow, i totally didn't realise that i did not post the error message correctly, here it is:
UIVisualEffectView 0x155d51c30 is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by cwRichardKim** [comment]
ah. yea so basically I have a UIVisualEffectView that can be applied ontop of the coverviewphoto (the larger one). that value has to be 1 if you want the effect to work. if you're not using it, it's not a problem

**Comment by Knights22** [comment]
ahhhhh, Thank you for the quick response and the cool project.
