### ISSUE TITLE
Provide example of subview

### ISSUE THREAD

**Issue by tawrahim** [cwRichardKim/RKCardView#9]
Do you mind providing an example snippet of how the content view was added to this card?
![Example](http://i.imgur.com/YVaSExwl.png)

**Comment by cwRichardKim** [comment]
Sorry, I actually totally scrapped that project during one of my clenses.  You treat it as a normal view though.  So you would create a UIView, add the view as a subview and place it using whatever method (constraints, programmatically, autolayout, etc)
